kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: httpd
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress

